# Generated by Django 2.2.12 on 2021-04-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='somemodel',
            old_name='tagline',
            new_name='damn',
        ),
    ]
