# Generated by Django 2.2.12 on 2021-04-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_auto_20210408_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='somemodel',
            new_name='Post',
        ),
    ]
