# Generated by Django 2.2.12 on 2021-04-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_auto_20210409_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
