# Generated by Django 2.2.12 on 2021-04-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_auto_20210409_0738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post17',
            new_name='Post',
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
        migrations.DeleteModel(
            name='Post10',
        ),
        migrations.DeleteModel(
            name='Post11',
        ),
        migrations.DeleteModel(
            name='Post12',
        ),
        migrations.DeleteModel(
            name='Post13',
        ),
        migrations.DeleteModel(
            name='Post14',
        ),
        migrations.DeleteModel(
            name='Post15',
        ),
        migrations.DeleteModel(
            name='Post16',
        ),
        migrations.DeleteModel(
            name='Post18',
        ),
        migrations.DeleteModel(
            name='Post19',
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
        migrations.DeleteModel(
            name='Post20',
        ),
        migrations.DeleteModel(
            name='Post3',
        ),
        migrations.DeleteModel(
            name='Post4',
        ),
        migrations.DeleteModel(
            name='Post5',
        ),
        migrations.DeleteModel(
            name='Post6',
        ),
        migrations.DeleteModel(
            name='Post7',
        ),
        migrations.DeleteModel(
            name='Post8',
        ),
        migrations.DeleteModel(
            name='Post9',
        ),
    ]
