# Generated by Django 2.2.12 on 2021-04-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0005_auto_20210410_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='idd',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
