# Generated by Django 2.2.12 on 2021-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0006_post_idd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.TextField()),
                ('desc', models.TextField()),
                ('news', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
    ]
